double exp_alt(double);
double exp_alt_core(double);
double pow_alt(double, double);
double pow_d_i_alt(double, int);
long long int pow_i_i_alt(int, int);
long long int lli_min;
long long int lli_max;
const double M_E_alt;
double ln_alt(double);
double ln_alt_core(double);
